open: {id:"tianmao-source-url",name:"天猫手工源码",link:"input",timeout:15,threads:1,major:true,brower:"phantomjs",urlhandler:"TianmaoListUrl",help:"1.【采集输入】只放需要转换的excel所在的目录路径\n2.软件只识别excel的表头字段：姓名，公司，电话\n3.点击启动，批量导入通讯录的文件默认生成在excel所在的目录下",remark:"通用链接图片采集"}
   text: {name:"链接"}
